#!/bin/sh
#

case "$1" in
	start)
		if [ -x /usr/sbin/vpnclient ]; then
		    /usr/sbin/vpnclient start
		fi
		;;
	stop)
		if [ -x /usr/sbin/vpnclient ]; then
		    /usr/sbin/vpnclient stop
		fi
		;;
	*)
		echo "Usage: $0 {start|stop}"
		exit 1
esac
