#!/bin/sh

UBIMTD=/dev/mtd6
UBIPART=/dev/ubi0
UBIDEV=${UBIPART}_0

if [ ! -e $UBIDEV ]; then
    mount /proc
    mount /sys
    if [ ! -e $UBIPART ]; then
	ubiformat $UBIMTD
	ubiattach -p $UBIMTD
    fi
    ubimkvol $UBIPART -m -N overlay
    umount /sys
    umount /proc
fi

mount -t ubifs $UBIDEV /overlay
#mount -t tmpfs none /overlay
mount -t overlayfs -o lowerdir=/,upperdir=/overlay overlayfs /rootfs_rw

cd /rootfs_rw
mount --bind /dev dev
pivot_root . rootfs_ro
exec chroot . /sbin/init
/bin/sh
